version = "3.5.3"
runner.dialect = scala213

docstrings = JavaDoc

maxColumn = 120

align = none
align.tokens = []
align.openParenCallSite = false
align.openParenDefnSite = false

continuationIndent.callSite = 2
continuationIndent.defnSite = 2

danglingParentheses = true

// Disabled due to https://github.com/scalameta/scalafmt/issues/1407
// includeNoParensInSelectChains = true

optIn.breakChainOnFirstMethodDot = true

newlines.alwaysBeforeTopLevelStatements = true

optIn.configStyleArguments = true

rewrite.rules = [
  AvoidInfix
  SortImports
  SortModifiers
  RedundantParens
  RedundantBraces
  PreferCurlyFors
]

project.includeFilters = [
  ".*\\.scala$"
]
